version: '2.2'
services:
  es-redis:
    build: ./redis
    image: es-redis:5.0.7
    container_name: es-redis
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/redis/:/data
      - /home/operation/data/logs/redis:/var/log/redis
    networks:
      elastic-network:
        ipv4_address: 172.18.0.12
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.router-redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.router-redis.entrypoints=entrypoint-redis"
      - "traefik.tcp.routers.router-redis.service=frontend-redis@docker"
      - "traefik.tcp.services.frontend-redis.loadbalancer.server.port=6379"

  es-grafana:
    image: grafana/grafana:6.5.2
    container_name: es-grafana
    environment:
      - GF_SERVER_DOMAIN=monitor.nanoit.kr
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SECURITY_ADMIN_USER=nanoit
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_METRICS_ENABLED=true
        #- GF_METRICS_BASIC_AUTH_USERNAME=${USERNAME}
        #- GF_METRICS_BASIC_AUTH_PASSWORD=${PASSWORD}
      - GF_ANALYTICS_REPORTING_ENABLED=false
        #- GF_INSTALL_PLUGINS=${PLUGINS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - es-mt01
    networks:
      elastic-network:
        ipv4_address: 172.18.0.13
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elastic-network"
      - "traefik.http.services.dashboard-grafana.loadbalancer.server.port=3000"

      - "traefik.http.routers.router-grafana.rule=Host(`monitor.nanoit.kr`) && (PathPrefix(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.router-grafana.entrypoints=entrypoint-http"
      - "traefik.http.routers.router-grafana.middlewares=stripprefix-grafana@docker"
      - "traefik.http.middlewares.stripprefix-grafana.stripprefix.prefixes=/grafana"
        
      #- "traefik.http.routers.router-grafana.middlewares=redirect-to-https@docker"
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=entrypoint-https"

        #- "traefik.http.routers.secured-grafana.rule=Host(`monitor.nanoit.kr`) && PathPrefix(`/grafana`)"
        #- "traefik.http.routers.secured-grafana.entrypoints=entrypoint-https"
        #- "traefik.http.routers.secured-grafana.service=dashboard-grafana@docker"
        #- "traefik.http.routers.secured-grafana.tls=true"
        #- "traefik.http.routers.secured-grafana.tls.certresolver=nanoit-cert"
        #- "traefik.http.routers.secured-grafana.middlewares=stripprefix-grafana"
        #- "traefik.http.middlewares.stripprefix-grafana.stripprefix.prefixes=/grafana,/grafana/"

        #- "traefik.http.routers.secured-grafana.rule=Host(`monitor.nanoit.kr`)"
        #- "traefik.http.routers.secured-grafana.entrypoints=entrypoint-grafana"
        #- "traefik.http.routers.secured-grafana.service=dashboard-grafana@docker"
        #- "traefik.http.routers.secured-grafana.tls=true"
        #- "traefik.http.routers.secured-grafana.tls.certresolver=nanoit-cert"
        #- "traefik.http.routers.secured-grafana.middlewares=stripprefix-grafana"
        #- "traefik.http.middlewares.stripprefix-grafana.stripprefix.prefixes=/grafana"
        
  es-mt01:
    build: ./elasticsearch
    image: elasticsearch:7.5.1
    container_name: es-mt01
    environment:
      - network.host=_site_
      - node.name=es-mt01
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/master01/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/master01:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.2

  es-mt02:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-mt02
    environment:
      - network.host=_site_
      - node.name=es-mt02
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/operation/data/elasticsearch/master02/:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/logs/elasticsearch/master02:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.3

  es-mt03:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-mt03
    environment:
      - network.host=_site_
      - node.name=es-mt03
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/master03/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/master03:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.4

  es-cdn01:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-cdn01
    environment:
      - network.host=_site_
      - node.name=es-cdn01
      - node.master=false
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/coordinate01/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/coordinate01:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.5

  es-cdn02:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-cdn02
    environment:
      - network.host=_site_
      - node.name=es-cdn02
      - node.master=false
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/coordinate02/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/coordinate02:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.6

  es-data01:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-data01
    environment:
      - network.host=_site_
      - node.name=es-data01
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/data01/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/data01:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.7

  es-data02:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-data02
    environment:
      - network.host=_site_
      - node.name=es-data02
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/data02/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/data02:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.8

  es-data03:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-data03
    environment:
      - network.host=_site_
      - node.name=es-data03
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/data03/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/data03:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.15

  es-ing01:
    build: ./elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: elasticsearch:7.5.1
    container_name: es-ing01
    environment:
      - network.host=_site_
      - node.name=es-ing01
      - node.master=false
      - node.data=false
      - node.ingest=true
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
      #- xpack.security.transport.ssl.enabled=true
      #- xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/operation/data/elasticsearch/ingest01/:/usr/share/elasticsearch/data
      - /home/operation/data/logs/elasticsearch/ingest01:/usr/share/elasticsearch/logs
    networks:
      elastic-network:
        ipv4_address: 172.18.0.14

  es-kib:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: es-kib
    environment:
      - server.name=es-kib
      - server.host=_site_
      - server.port=5601
      - elasticsearch.hosts=_site_
        #- server.basePath=/kibana
        #- server.rewriteBasePath=false
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /home/operation/data/logs/elasticsearch/kibana01/kibana.log:/usr/share/kibana/log
      - /etc/localtime:/etc/localtime:ro
    networks:
      elastic-network:
        ipv4_address: 172.18.0.9
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-data03']
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elastic-network"
      - "traefik.http.services.dashboard-kibana.loadbalancer.server.port=5601"

        #- "traefik.http.routers.router-kibana.rule=Host(`monitor.nanoit.kr`)"
        #- "traefik.http.routers.router-kibana.entrypoints=entrypoint-http"
        #- "traefik.http.routers.router-kibana.middlewares=redirect-to-https@docker"
        #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=entrypoint-https"

      - "traefik.http.routers.secured-kibana.rule=Host(`monitor.nanoit.kr`) && (PathPrefix(`/kibana`) || PathPrefix(`/kibana/`))"
      - "traefik.http.routers.secured-kibana.entrypoints=entrypoint-http"
      - "traefik.http.routers.secured-kibana.service=dashboard-kibana@docker"

        #- "traefik.http.routers.secured-kibana.tls=true"
        #- "traefik.http.routers.secured-kibana.tls.certresolver=nanoit-cert"
        #- "traefik.http.routers.secured-kibana.middlewares=stripprefix-kibana"
        #- "traefik.http.middlewares.stripprefix-kibana.stripprefix.prefixes=/kibana"
   
  es-idx:
    build: ./logstash
    image: logstash:7.5.1
    container_name: es-idx
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        #- ./logstash/pipeline/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      elastic-network:
        ipv4_address: 172.18.0.10
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-data03', 'es-kib']

  es-mtb:
    build: ./metricbeat
    image: metricbeat:7.5.1
    container_name: es-mtb
    command: -e
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/operation/data/logs/elasticsearch/metricbeat01:/usr/share/metricbeat/logs
      - /home/operation/data/elasticsearch/metricbeat01/:/usr/share/metricbeat/data
    environment:
      - name=LOG-MONITOR-SERVER
      - cap-add=sys_ptrace
      - cap-add=dac_read_search
    network_mode: host
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-kib', 'es-idx', 'es-data03']
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  es-htb:
    image: docker.elastic.co/beats/heartbeat:7.5.1
    container_name: es-htb
    command: ["-e", "--strict.perms=false"]
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - /home/operation/data/logs/elasticsearch/heartbeat01:/usr/share/heartbeat/logs
      - /home/operation/data/elasticsearch/metricbeat01/:/usr/share/heartbeat/data
    environment:
      - name=LOG-MONITOR-SERVER
    network_mode: host
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-kib', 'es-idx', 'es-data03']
    healthcheck:
      test: heartbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  es-ftb:
    build: ./filebeat
    image: filebeat_host:7.5.1
    container_name: es-ftb
    command: -e
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/operation/data/elasticsearch/filebeat01/:/usr/share/filebeat/data
      - /home/operation/data/logs/elasticsearch:/usr/share/filebeat/logs/elasticsearch
      - /home/operation/data/logs/elasticsearch/filebeat01:/usr/share/filebeat/logs/filebeat01
      - /home/operation/data/logs/traefik:/usr/share/filebeat/logs/traefik
      - /home/operation/data/redis/redis.log:/usr/share/filebeat/logs/redis/redis.log
      - /var/log:/usr/share/filebeat/logs/system
    network_mode: host
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-kib', 'es-idx', 'es-data03']
    command: ["--strict.perms=false"]
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

networks:
  elastic-network:
    external: true
