version: '2.2'
services:
  redis-es:
    build: ./redis
    image: es-redis:5.0.7
    container_name: redis-es
    sysctls:
      - net.core.somaxconn=511
    ports:
      - 8579:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/redis/:/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.12

  grafana-es:
    image: grafana/grafana:6.5.2
    container_name: grafana-es
    ports:
      - "8430:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      elastic-network:
        ipv4_address: 172.18.0.13
    depends_on:
      - es-mt01

  es-mt01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-mt01
    environment:
      - network.host=_site_
      - node.name=es-mt01
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/master01/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      elastic-network:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  es-mt02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-mt02
    environment:
      - network.host=_site_
      - node.name=es-mt02
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch/master02/:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      elastic-network:
        ipv4_address: 172.18.0.3

  es-mt03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-mt03
    environment:
      - network.host=_site_
      - node.name=es-mt03
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/master03/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.4

  es-cdn01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-cdn01
    environment:
      - network.host=_site_
      - node.name=es-cdn01
      - node.master=false
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/coordinate01/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.5

  es-cdn02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-cdn02
    environment:
      - network.host=_site_
      - node.name=es-cdn02
      - node.master=false
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/coordinate02/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.6

  es-data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-data01
    environment:
      - network.host=_site_
      - node.name=es-data01
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/data01/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.7

  es-data02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-data02
    environment:
      - network.host=_site_
      - node.name=es-data02
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/data02/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.8

  es-data03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-data03
    environment:
      - network.host=_site_
      - node.name=es-data03
      - node.master=false
      - node.data=true
      - node.ingest=false
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/data03/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.15

  es-ing01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es-ing01
    environment:
      - network.host=_site_
      - node.name=es-ing01
      - node.master=false
      - node.data=false
      - node.ingest=true
      - cluster.remote.connect=false
      - cluster.name=nanoit-log-cluster
      - discovery.seed_hosts=es-mt01,es-mt02,es-mt03
      - cluster.initial_master_nodes=es-mt01,es-mt02,es-mt03
      - bootstrap.memory_lock=true
 #     - xpack.security.transport.ssl.enabled=true
 #     - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/elasticsearch/ingest01/:/usr/share/elasticsearch/data
    networks:
      elastic-network:
        ipv4_address: 172.18.0.14

  es-kib:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: es-kib
    environment:
      - server.host=_site_
      - elasticsearch.hosts=_site_
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    networks:
      elastic-network:
        ipv4_address: 172.18.0.9
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-data03', 'es-ing01']
   
  es-lgs-idx:
    build: ./logstash
    image: logstash:7.5.1
    container_name: es-lgs-idx
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
    networks:
      elastic-network:
        ipv4_address: 172.18.0.10
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-data03', 'es-ing01', 'es-kib']

  es-mtb-host:
    build: ./metricbeat_host
    image: metricbeat_host:7.5.1
    container_name: es-mtb-host
    command: -e
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - name=LOG-MONITOR-SERVER
      - cap-add=sys_ptrace
      - cap-add=dac_read_search
    network_mode: host
    depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-kib', 'es-lgs-idx', 'es-ing01', 'es-data03']
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
      retries: 5
    
      #es-mtb-ctn:
      #build: ./metricbeat_container
      #image: metricbeat_container:7.5.1
      #container_name: es-mtb-ctn
      #command: -e
      #user: root
      #depends_on: ['es-mt01', 'es-mt02', 'es-mt03', 'es-cdn01', 'es-cdn02', 'es-data01', 'es-data02', 'es-kib', 'es-lgs-idx', 'es-ing01', 'es-data03']
      #environment:
      #- http.enabled=true
      #- name=LOG-MONITOR-SERVER
      #volumes:
      #- /etc/localtime:/etc/localtime:ro
      #networks:
      #elastic-network:
      #ipv4_address: 172.18.0.11
      #healthcheck:
      #test: metricbeat test config
      #interval: 30s
      #timeout: 15s
      #retries: 5

networks:
  elastic-network:
    external: 
      name: elastic-network
