metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.period: 30s
    reload.enabled: false

metricbeat.max_start_delay: 30s

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

setup:
  kibana.host: "172.18.0.1:9200"
  template.settings:
    index.number_of_shards: 1
    index.codec: best_compression
  dashboards:
    enabled: true
    always_kibana: true
    retry.enabled: true

output.elasticsearch:
  hosts: ["172.18.0.1:9200"]

backoff.init: 5s

backoff.max: 60s

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - add_kubernetes_metadata: ~
