#- pipeline.id: test
#  pipeline.workers: 1
#  pipeline.batch.size: 1
#  config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"

- pipeline.id: filebeat
  #queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/filebeat.conf"
- pipeline.id: metricbeat
  #queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/metricbeat.conf"
- pipeline.id: heartbeat
  #queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/heartbeat.conf"
- pipeline.id: packetbeat
  #queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/packetbeat.conf"

  #pipeline.id: mylogs
  #config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
  #path.config: "/etc/conf.d/logstash/myconfig.cfg"
  #pipeline.workers: 1 (actually defaults to number of CPUs)
  #pipeline.batch.size: 125
  #pipeline.batch.delay: 50
  #queue.type: memory
  #queue.page_capacity: 64mb
  #queue.max_events: 0
  #queue.max_bytes: 1024mb
  #queue.checkpoint.acks: 1024
  #queue.checkpoint.writes: 1024
  #queue.checkpoint.interval: 1000
  #dead_letter_queue.enable: false
  #dead_letter_queue.max_bytes: 1024mb
  #path.dead_letter_queue:
